version: '3.8'

services:
  authservice:
    build: 
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - "5079:80"
      - "7135:443"
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Zx02071990
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx
      - ConnectionStrings__DefaultConnection=Host=UserPGDB;Port=5432;Database=postgres;Username=postgres;Password=!Zx02071990
      - JWT_SECRET_KEY=!Ghjuhfvvbcn02071990
      - JWT_ISSUER=cs_shop
      - JWT_AUDIENCE=cs_shop_users
    depends_on:
      - db
      - redis

  itemservice:
    build: 
      context: .
      dockerfile: ItemService/Dockerfile
    ports:
      - "7136:80"
      - "7137:443"
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Zx02071990
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx
      - ConnectionStrings__DefaultConnection=Host=UserPGDB;Port=5432;Database=postgres;Username=postgres;Password=!Zx02071990
      - JWT_SECRET_KEY=!Ghjuhfvvbcn02071990
      - JWT_ISSUER=cs_shop
      - JWT_AUDIENCE=cs_shop_users
    depends_on:
      - db
      - redis

  db:
    image: postgres
    container_name: UserPGDB
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "!Zx02071990"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
